#!/bin/bash

if [ -z "$1" ]; then
  echo "¯\_(ツ)_/¯"
else
  docker-machine create -d "virtualbox" --virtualbox-memory "2048" $1
  docker-machine ssh $1 sudo sysctl -w vm.max_map_count=262144

  if [ -z "$2" ]; then
    echo "docker swarm init"
    docker-machine ssh $1 docker swarm init --advertise-addr `docker-machine ip $1`
  else
    echo "docker swarm join"
    docker-machine ssh $1 docker swarm join --token `docker-machine ssh $2 docker swarm join-token -q ${3:-worker}` `docker-machine ip $2`:2377
  fi
fi
